# -*- coding: utf-8 -*-
"""Verificador de Cartao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/eresmatador125/3de367e7dd1d45d776e11b370dffe78e/verificador-de-cartao.ipynb

# Trabalho 2 bimestre

### Aluno: Caio Schneider de Sousa


### Objetivo fazer um algoritimo de Luhn, validador de cartao de credito
codigo baseado no link do video "https://www.youtube.com/watch?v=dF7wNjsRBjI" do pset-1, com os cartões american Express, Master Card e Visa,
"""

#Algoritmo de Luhn
print("Olá, Iniciamos o Verificador de Catão")
digitos = []
cartao = int(input("\nDigite o numero do seu cartao: "))

#gerando numeros interos em uma lista 
while cartao > 0:
    digitos.insert(0, cartao % 10)
    cartao = (cartao - cartao % 10) //10

#separando os numeros para somar e multiplicar.
passo1 = []
passo2 = []
passo1 = digitos[1::2]
passo2 = digitos[::2]

#somatoria para verificar o cartao 
soma1 = 0
soma2 = 0
for i in passo1:
    soma1 += i
for i in range(len(passo2)):
    valormaior = passo2[i] * 2
    if valormaior > 9:
        valormaior = valormaior - 9  
    soma2 += valormaior

somaTotal = soma1 + soma2

#verificar qual cartao é de que bandeira, e validar cartão
if somaTotal % 10 == 0:
    if len(digitos) == 15 and (digitos[0:2] == [3,4] or digitos[0:2] == [3,7]):
        print("\n Seu Cartao é American Express")
    elif len(digitos) == 16 and (digitos[0:2] == [5,1] or digitos[0:2] == [5,2] or digitos[0:2] == [5,3] or digitos[0:2] == [5,4] or digitos[0:2] == [5,5]):
        print("\n Seu Cartao é Master Card")
    elif (len(digitos) == 16 or len(digitos) == 13) and digitos[0] == 4:
        print("\n Seu Cartao é Visa")
    else:
        print("cartao invalido. Numero de Cartao ou Bandeira Nao Aceitavel")
else:
    print("Cartao Invalido. Codigo Verificador Invalido.")

#verificar manualmente o codigo do cartao
print(passo1) #somar todos os numeros
print(passo2) #multiplicar cada numero por dois e somar os menores que 10, os maiores diminuir 9